<?php
$helper = $this->helper("Lof\Formbuilder\Helper\Fields");
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = $helper->getFieldPrefix() . $cid;
$available_fields = $helper->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type]) ? $available_fields[$field_type] : '';
$validates = $field_validate;
$field_help = isset($options['description']) ? $options['description'] : '';
if ($field_validate && is_array($field_validate)) {
    $validates = implode(" ", $field_validate);
}
$image_type = isset($options['image_type']) ? $options['image_type'] : 'png,jpg,gif,jpeg,zip,doc,pdf';
$image_maximum_size = isset($options['image_maximum_size']) ? $options['image_maximum_size'] : 10;
?>
<div class="subtemplate-wrapper">
    <label for="<?php echo $field_name; ?>"
           class="<?php echo (1 == $required) ? 'required' : ''; ?>"><?php echo $label; ?><?php echo (1 == $required) ? '<em>*</em>' : ''; ?></label>
    <div class="input-box">
        <input name="form_file_<?php echo $cid ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>"
               class="input-text<?php echo (1 == $required) ? ' required-entry' : ''; ?> <?php echo $validates; ?>"
               type="file"/>
        <?php if ($field_help) { ?>
            <span class="help-block"><?php echo $field_help; ?></span>
        <?php } ?>
    </div>
</div>