<?php
$helper = $this->helper("Lof\Formbuilder\Helper\Fields");
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = $helper->getFieldPrefix() . $cid;
$available_fields = $helper->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type]) ? $available_fields[$field_type] : '';
$validates = $field_validate;
$field_help = isset($options['description']) ? $options['description'] : '';
if ($field_validate && is_array($field_validate)) {
    $validates = implode(" ", $field_validate);
}
$min = isset($options['min']) ? (int)$options['min'] : 1;
$max = isset($options['max']) ? (int)$options['max'] : 10;
$units = isset($options['units']) ? $options['units'] : '';
$integer_only = isset($options['integer_only']) ? $options['integer_only'] : '';
if ($integer_only) {
    $validates .= ' validate-digits';
}
?>
<div class="subtemplate-wrapper">
    <label for="<?php echo $field_name; ?>"
           class="<?php echo (1 == $required) ? 'required' : ''; ?>"><?php echo $label; ?><?php echo (1 == $required) ? '<em>*</em>' : ''; ?></label>
    <div class="row">
        <div class="input-box <?php echo isset($field['fieldcol']) ? 'col-sm-' . $field['fieldcol'] : 'col-sm-12'; ?>">
            <input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>"
                   value="<?php echo ($form_data && isset($form_data[$field_name])) ? $form_data[$field_name] : ''; ?>"
                   class="input-text <?php echo (1 == $required) ? 'required-entry' : ''; ?> <?php echo $validates . ' validate-min-max ' . ($min > 0 ? 'minimum-length-' . $min : ''); ?> <?php echo($max > 0 ? 'maximum-length-' . $max : ''); ?>"
                   type="text"/>
            <?php
            if ($units != '') {
                echo $units;
            }
            ?>
            <?php if ($field_help) { ?>
                <span class="help-block"><?php echo $field_help; ?></span>
            <?php } ?>
        </div>
    </div>
</div>