<?php
$helper = $this->helper("Lof\Formbuilder\Helper\Fields");
$dataHelper = $this->helper("Lof\Formbuilder\Helper\Data");
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = $helper->getFieldPrefix() . $cid;
$available_fields = $helper->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type]) ? $available_fields[$field_type] : '';
$validates = $field_validate;
$field_help = isset($options['description']) ? $options['description'] : '';
if ($field_validate && is_array($field_validate)) {
    $validates = implode(" ", $field_validate);
}
$currency_symbol = $dataHelper->getSymbol();

$size = isset($options['size']) ? $options['size'] : '';
?>
<div class="subtemplate-wrapper">
    <label for="<?php echo $field_name; ?>"
           class="<?php echo (1 == $required) ? 'required' : ''; ?>"><?php echo $label; ?><?php echo (1 == $required) ? '<em>*</em>' : ''; ?></label>
    <div class="input-box">
        <div class="form-currency"><?php echo $currency_symbol; ?></div>
        <div class="row form-input">
            <div class="form-input1 <?php echo isset($field['fieldcol']) ? 'col-sm-' . $field['fieldcol'] : 'col-sm-12'; ?>">
                <input name="<?php echo $field_name; ?>" id="<?php echo $field_name; ?>" title="<?php echo $label; ?>"
                       value="<?php echo ($form_data && isset($form_data[$field_name])) ? $form_data[$field_name] : ''; ?>"
                       placeholder="00.00"
                       class="input-text <?php echo (1 == $required) ? 'required-entry' : ''; ?> <?php echo $validates; ?> <?php echo $size; ?>"
                       type="text"/>
            </div>
        </div>
        <?php if ($field_help) { ?>
            <span class="help-block"><?php echo $field_help ?></span>
        <?php } ?>
    </div>
</div>