<?php
$helper = $this->helper("Lof\Formbuilder\Helper\Fields");
$form_data = $this->getData('form_data');
$field = $this->getData('field_data');
$field_type = $field['field_type'];
$label = $field['label'];
$options = $field['field_options'];
$required = $field['required'];
$cid = $field['cid'];
$field_name = $helper->getFieldPrefix() . $cid;
$available_fields = $helper->getAvailableFields();
$html = '';
$field_validate = isset($available_fields[$field_type]) ? $available_fields[$field_type] : '';
$validates = $field_validate;
$field_help = isset($options['description']) ? $options['description'] : '';
if ($field_validate && is_array($field_validate)) {
    $validates = implode(" ", $field_validate);
}
$id = $cid . time();
?>
<div class="subtemplate-wrapper">
    <label for="<?php echo $field_name; ?>"
           class="<?php echo (1 == $required) ? 'required' : ''; ?>"><?php echo $label; ?><?php echo (1 == $required) ? '<em>*</em>' : ''; ?></label>
    <div class="input-box">
        <div class="input-line">
			<span class="hours">
				<select name="<?php echo $field_name . '_hours'; ?>" id="<?php echo $field_name . '_hours'; ?>"
                        class="<?php echo (1 == $required) ? 'required-entry' : ''; ?> validate-zero-or-greater time-<?php echo $id ?>">
					<?php
                    for ($i = 0; $i < 24; $i++) {
                        $k = $i;
                        if ($i < 10) {
                            $k = '0' . $i;
                        } ?>
                        <option value="<?php echo $k; ?>"><?php echo $k; ?></option>
                        <?php
                    }
                    ?>
				</select>
				<label><?php echo __("HH"); ?></label>
			</span>
            <span class="above-line">:</span>
            <span class="minutes">
				<select name="<?php echo $field_name . '_minutes'; ?>" id="<?php echo $field_name . '_minutes'; ?>"
                        class="<?php echo (1 == $required) ? 'required-entry' : ''; ?> validate-zero-or-greater time-<?php echo $id ?>">
					<?php
                    for ($i = 0; $i < 60; $i++) {
                        $k = $i;
                        if ($i < 10) {
                            $k = '0' . $i;
                        } ?>
                        <option value="<?php echo $k; ?>"><?php echo $k ?></option>
                    <?php }
                    ?>

					</select>
					<label><?php echo __("MM"); ?></label>
				</span>
            <span class="above-line">:</span>
            <span class="seconds">
					<select name="<?php echo $field_name . '_seconds'; ?>" id="<?php echo $field_name . '_seconds'; ?>"
                            class="<?php echo (1 == $required) ? 'required-entry' : ''; ?> validate-zero-or-greater time-<?php echo $id ?>">
						<?php
                        for ($i = 0; $i < 60; $i++) {
                            $k = $i;
                            if ($i < 10) {
                                $k = '0' . $i;
                            } ?>
                            <option value="<?php echo $k; ?>"><?php echo $k; ?></option>
                        <?php }
                        ?>
						</select>
						<label><?php echo __("SS"); ?></label>
					</span>
            <span class="am_pm">
						<select name="<?php echo $field_name . '_am_pm'; ?>" id="<?php echo $field_name . '_am_pm'; ?>"
                                class="time-<?php echo $id ?>">
							<option value="AM"><?php echo __("AM"); ?></option>
							<option value="PM"><?php echo __("PM"); ?></option>
						</select>
					</span>
        </div>
        <?php if ($field_help) { ?>
            <span class="help-block"><?php echo $field_help; ?></span>
        <?php } ?>
    </div>
</div>