<div class="container">
    <div class="row">
        <div class="col col-xs-12 col-sm-6">
            <i class="fa fa-truck"></i> <strong>Gratis bezorging of afhalen</strong><br/>
            <small>Voor 17:00 besteld, volgende werkdag in huis</small>
        </div>
        <div class="col col-xs-12 col-sm-6">
            <i class="fa fa-clock-o"></i> <strong>Altijd 14 dagen bedenktijd</strong><br/>
            <small>Na ontvangst van uw bestelling</small>
        </div>
        <div style="clear: both" class="visible-xs"></div>
        <div class="col col-xs-12 col-sm-6">
            <i class="fa fa-credit-card"></i> <strong>Veilig (achteraf) betalen</strong><br/>
            <small>iDEAL, creditcard, PayPal of AfterPay</small>
        </div>
        <div class="col col-xs-12 col-sm-6">
            <i class="fa fa-phone"></i> <strong>Vriendelijke klantenservice</strong><br/>
            <small>via <a href="callto:0031703251272">070-3251272</a></small>
        </div>
    </div>
</div>
