<h2>Dames-Heren merken</h2>
<?php
if( $this->getHelper()->isEnabled() ) : ?>
<?php
$is_toolbar = $this->getConfig()->getCurrentStoreConfigValue('manufacturer/pagination_settings/add_toolbar_brand_list');
if( $is_toolbar ){
	$_manufacturerCollection = $this->getCollection()->addFieldToFilter('manufacturer_name', array('nlike' => '%KIDS'));
} else {
	$_manufacturerCollection = $this->getCollection()->addFieldToFilter('manufacturer_name', array('nlike' => '%KIDS'));
}

if (!$_manufacturerCollection->count()) :
	?>
<div class="message info empty">
	<div><?php echo __('No Manufacutrer\'s Found!'); ?></div>
</div>
<?php else: ?>
	<?php
	if( $this->getConfig()->getCurrentStoreConfigValue('manufacturer/manufacturer_slider/slider_enabled') ) {
		$cnt = $_manufacturerCollection->count();
		if( $cnt !== 0 ) : ?>
			<div class="manufacturer-slider">
				<?php echo $this->getLayout()->createBlock('\Biztech\Manufacturer\Block\Manufacturer\Index')
				->setTemplate('manufacturer/manufacturer_slider.phtml')
				->toHtml();
				?>
			</div>
		<?php endif;
	}

	$alphas = range('A', 'Z');
	$_manufacturerInitials = array();

	foreach ($_manufacturerCollection as $_manufacturer) {
		if ((substr($_manufacturer->getManufacturerName(), -4)=='KIDS')) {
			continue;
		}
		$_manufacturerInitials[] = strtolower(substr($_manufacturer->getBrandName(),0,1));
	}
	$nav = array();
	foreach ($alphas as $key) {
		if( in_array(strtolower($key), $_manufacturerInitials) ){
			$class = '';
			if( $key == 'A' )
				$class = 'first';
			$nav[$key] = array(
				'class' => $class,
			);
		} else {
			$class = 'disable';

			$nav[$key] = array(
				'class' => $class,
			);
		}
	}

	?>
	<div class="alphabet">
		<?php
		// echo $navigation;
		foreach ($nav as $key => $value) {
			echo '<a class="'.$value['class'].'" href="javascript:void(0)">'.$key.'</a>';
		}
		?>
		<a class="last active" href="javascript:void(0)">All</a>
	</div>

	<div class="manufacturer-collection">
		<?php
		if( $is_toolbar ) {
			echo $block->getToolbarHtml();
			echo $block->getAdditionalHtml();

			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
		}else {
			$viewMode = 'grid';
			$image = 'category_page_grid';
			$showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$pos = $block->getPositioned();
		}
		?>

		<div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
			<?php $iterator = 1; ?>
			<ol id="manufacturer-list" class="products list items product-items">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_manufacturerCollection as $_manufacturer):
					if ((substr($_manufacturer->getManufacturerName(), -4)=='KIDS')) {
						continue;
					}
				 ?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-grid">
						<?php
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
							. 'top:' . $productImage->getHeight() . 'px;"';
						}
						$imageUrl = $this->getHelper()->getImageUrl($_manufacturer->getFilename(), 'large_thumb');
						if( $imageUrl &&
							($this->getConfig()->getCurrentStoreConfigValue('manufacturer/manufacturer_brand_list/manufacturer_display_logo_name') == 0 || $this->getConfig()->getCurrentStoreConfigValue('manufacturer/manufacturer_brand_list/manufacturer_display_logo_name') == 2 )
							) :
							?>

							<a class="product photo product-item-photo" tabindex="-1" href="<?php echo trim($this->getManufacturerUrl($_manufacturer), '/') ?>">
								<?php
								echo $this->getLayout()->createBlock('\Magento\Framework\View\Element\Template')
								->setManufacturerImage($imageUrl)
								->setManufacturerName($_manufacturer->getBrandName())
								->setManufacturerConfig($this->getConfig())
								->setImageType('large_thumb')
								->setTemplate('Biztech_Manufacturer::manufacturer/manufacturer_resize.phtml')
								->toHtml();


								?>
							</a>
						<?php endif;
						if( $this->getConfig()->getCurrentStoreConfigValue('manufacturer/manufacturer_brand_list/manufacturer_display_logo_name') == 0 || $this->getConfig()->getCurrentStoreConfigValue('manufacturer/manufacturer_brand_list/manufacturer_display_logo_name') == 1 ) :
							?>
						<div class="product-shop">
							<div class="f-fix">
								<h2 class="product-name">
									<a href="<?php echo trim($this->getManufacturerUrl($_manufacturer), '/') ?>">
										<?php echo $_manufacturer->getBrandName() ?>
									</a>
								</h2>
							</div>
						</div>
					<?php endif; ?>
				</div>
				<?php echo($iterator == count($_manufacturerCollection) + 1) ? '</li>' : '' ?>
			<?php endforeach; ?>
		</ol>

	</div>
	<?php
	/*if( $is_toolbar ){
		echo $block->getToolbarHtml();
		echo $block->getPagerHtml();
	}*/
	?>
</div>
<?php endif; ?>

<?php endif; ?>
<script type="text/javascript">
	require([
		'jquery'
		],function(jQuery){
			var _alphabets = jQuery('.alphabet > a');

			_alphabets.click(function(){
				var _letter = jQuery(this), _text = jQuery(this).text(), _count = 0;
				_alphabets.removeClass('active');
				_letter.addClass('active');
				// _letter.toggleClass('alpha-select');
				jQuery.ajax({
					url : '<?php echo $this->getBaseUrl().'merken/damesheren/ajax'?>',
					type : 'POST',
					data : {char : _text, brandtype : 'general', viewMode : '<?php echo isset($viewMode)? $viewMode : '';?>'},

					showLoader: true,
					success : function(data){
						jQuery('.loading-mask').hide();
						jQuery('.manufacturer-collection').html(data);
					},
					complete : function(){
						window.optimizeImage();
					}
				});
			});

		});
	</script>
