<?php
$style = '';
$helper = $this->helper("Lof\Formbuilder\Helper\Data");
$form = $block->getCurrentForm();
$fields = $form->getFields();
$modId = time() . rand();
$reCaptchaPublicKey = $block->getConfig("general_settings/captcha_publickey");
$reCaptchaPrivateKey = $block->getConfig("general_settings/captcha_privatekey");
$before_form_content = $helper->filter($form->getData('before_form_content'));
$after_form_content = $helper->filter($form->getData('after_form_content'));

$button_text = $this->getData('button_text');
$show_text_before = $this->getData('show_text_before');
$show_text_after = $this->getData('show_text_after');
$prefix_class = $this->getData('prefix_class');
$display_type = $this->getData('display_type');
$popup_width = $this->getData('popup_width');
$popup_height = $this->getData('popup_height');
$title = $this->getData('title');
$show_after = (int)$this->getData('show_after');
$show_cookietime = $this->getData('show_cookietime');

$blockId = time() . rand();
if ($display_type == 'popup' || $display_type == 'link') $style .= 'display: none;';
if ($style != '') $style = 'style="' . $style . '"';
?>
<a href="#" class="btnfancy"
   <?php if ($display_type == 'link'){ ?>style="display: none"<?php } ?>><?php echo $button_text ?></a>
<div id="lofform<?php echo $modId ?>" class="formbuilder-form <?php echo $prefix_class ?>" <?php echo $style ?>>
    <?php if ($title) { ?><h2 class="text-center"><?php echo $title ?></h2><?php } ?>
    <?php if ($show_text_before && ($before_form_content != '')) { ?>
        <div class="before-form-content">
            <?php echo $before_form_content; ?>
        </div>
    <?php } ?>
    <form id="formbuilder<?php echo $modId ?>" class="formbuilder form" action="<?php echo $block->getFormAction(); ?>"
          id="formbuilder-form<?php echo $modId ?>" method="post"
          data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'
          enctype="multipart/form-data">
        <?php if ($fields) { ?>
            <div class="form-list row">
                <?php foreach ($fields as $field) { ?>
                    <div class="field <?php echo isset($field['wrappercol']) ? 'col-sm-' . $field['wrappercol'] : 'col-sm-12'; ?> <?php if ($field['field_type'] == 'section_break' && $field['show_breakline'] == 2) {
                        echo 'hidden';
                    } ?>">
                        <div class="response-field-<?php echo $field['field_type'] ?>">
                            <?php echo $block->getField($field['field_type'], $field); ?>
                        </div>
                    </div>
                <?php } ?>
                <?php if ($form->getShowCaptcha()) { ?>
                    <div class="field col-sm-12">
                        <div class="g-recaptcha" data-sitekey="<?php echo $reCaptchaPublicKey ?>"></div>
                    </div>
                <?php } ?>
                <input type="hidden" name="return_url" value="<?php echo $block->getCurrentUrl() ?>"/>
            </div>
        <?php } ?>
        <div class="row">
            <div class="buttons-set col-sm-12">
                <input type="hidden" name="formId" id="hideit" value="<?php echo $form->getId(); ?>"/>
                <button type="submit" title="<?php echo __('Submit') ?>" class="formbuilder-button button">
                    <span><span><?php echo __('Submit') ?></span></span></button>
                <?php if ($submit_button_text = $form->getSubmitButtonText()) { ?>
                    <div class="clear"><?php echo $submit_button_text; ?></div>
                <?php } ?>
            </div>
        </div>
    </form>
    <?php if ($form->getShowCaptcha()) { ?>
        <script src='https://www.google.com/recaptcha/api.js'></script>
    <?php } ?>
    <?php if ($show_text_after && ($after_form_content != '')) { ?>
        <div class="before-form-content">
            <?php echo $after_form_content; ?>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'Lof_Formbuilder/js/jquery.cookie',
        'Ves_All/lib/fancybox/jquery.fancybox.pack',
        'mage/validation'
    ], function ($) {
        jQuery(document).ready(function ($) {
            jQuery(".btnfancy").fancybox({
                'href': '#lofform<?php echo $modId ?>',
                'titleShow': false,
                'transitionIn': 'elastic',
                'transitionOut': 'elastic',
                <?php if((int)$popup_width > 0){ ?>'maxWidth': '<?php echo $popup_width ?>',<?php } ?>
                <?php if((int)$popup_height > 0){ ?>'maxHeight': '<?php echo $popup_height ?>',<?php } ?>
            });
            <?php if($display_type == 'popup'){ ?>
            <?php if((int)$show_cookietime > 0){ ?>
            if (jQuery.cookie('form_status') != '1') {
                <?php } ?>
                setTimeout(function () {
                    jQuery('.btnfancy').trigger("click");
                }, <?php echo $show_after ?>);
                <?php if((int)$show_cookietime > 0){ ?>
                jQuery.cookie('form_status', '1', {expires: <?php echo (int)$show_cookietime ?>});
            }
            <?php } ?>
            <?php } ?>
            <?php if((int)$show_cookietime > 0 && $display_type == 'popup'){ ?>
            jQuery('#formbuilder<?php echo $modId ?>').validation().submit(function () {
                jQuery.cookie('form_status', '1', {expires: 720});
            });
            <?php } ?>
        });
    });
</script>