<ul>
    <li><i class="fa fa-truck"></i> Voor 17:00 besteld, de volgende werkdag <strong>gratis</strong> in huis</li>
    <li><i class="fa fa-clock-o"></i> 14 dagen bedenktijd</li>
    <li><i class="fa fa-credit-card"></i> Veilig betalen via iDEAL, creditcard, PayPal of Bancontact</li>
    <li><i class="fa fa-child"></i> Gratis afhalen in een van onze filialen</li>
    <li><i class="fa fa-phone"></i> Vriendelijke en betrouwbare service via <a href="callto:0031703251272">070-3251272</a></li>
</ul>
